# Generated by Django 6.0.4 on 2026-04-18 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feedback',
            name='core_feedba_created_e27107_idx',
        ),
    ]
