# Generated by Django 6.0.4 on 2026-04-28 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_feedback_redundant_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerScheduleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_doc_name', models.CharField(blank=True, max_length=255)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Power schedule batch',
                'verbose_name_plural': 'Power schedule batches',
                'ordering': ('-effective_start', '-published_at'),
            },
        ),
        migrations.CreateModel(
            name='PowerOutageSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('period_label', models.CharField(blank=True, max_length=64)),
                ('outage_group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C')], db_index=True, max_length=1)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.powerschedulebatch')),
            ],
            options={
                'verbose_name': 'Power outage slot',
                'verbose_name_plural': 'Power outage slots',
                'ordering': ('slot_date', 'start_time'),
                'indexes': [models.Index(fields=['batch', 'slot_date', 'outage_group'], name='core_powero_batch_i_169cb2_idx'), models.Index(fields=['slot_date', 'start_time'], name='core_powero_slot_da_01efe8_idx')],
                'unique_together': {('batch', 'slot_date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='PowerAreaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('city', models.CharField(blank=True, db_index=True, max_length=64)),
                ('area_name', models.CharField(db_index=True, max_length=255)),
                ('group_code', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C')], db_index=True, max_length=1)),
                ('aliases', models.TextField(blank=True, help_text='Comma-separated alternate spellings or names.')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_groups', to='core.powerschedulebatch')),
            ],
            options={
                'verbose_name': 'Power area group',
                'verbose_name_plural': 'Power area groups',
                'ordering': ('region', 'city', 'area_name'),
                'indexes': [models.Index(fields=['batch', 'region', 'city', 'group_code'], name='core_powera_batch_i_f50133_idx'), models.Index(fields=['batch', 'area_name'], name='core_powera_batch_i_d1ffe1_idx')],
                'unique_together': {('batch', 'area_name')},
            },
        ),
    ]
