# Generated by Django 6.0.4 on 2026-04-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_powerschedulebatch_poweroutageslot_powerareagroup'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='powerareagroup',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='powerareagroup',
            name='core_powera_batch_i_f50133_idx',
        ),
        migrations.RemoveIndex(
            model_name='powerareagroup',
            name='core_powera_batch_i_d1ffe1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='poweroutageslot',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='poweroutageslot',
            name='core_powero_batch_i_169cb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='poweroutageslot',
            name='core_powero_slot_da_01efe8_idx',
        ),
        migrations.RemoveField(
            model_name='poweroutageslot',
            name='batch',
        ),
        migrations.DeleteModel(
            name='PowerAreaGroup',
        ),
        migrations.DeleteModel(
            name='PowerOutageSlot',
        ),
        migrations.DeleteModel(
            name='PowerScheduleBatch',
        ),
    ]
