# Generated by Django 6.0.4 on 2026-04-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_powerareagroup_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=64)),
                ('district', models.CharField(blank=True, db_index=True, max_length=128)),
                ('area', models.CharField(db_index=True, max_length=255)),
                ('outage_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('source_file', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Power schedule',
                'verbose_name_plural': 'Power schedules',
                'ordering': ('outage_date', 'start_time', 'region', 'area'),
                'indexes': [models.Index(fields=['region', 'outage_date'], name='core_powers_region_19180c_idx'), models.Index(fields=['district', 'outage_date'], name='core_powers_distric_b52476_idx'), models.Index(fields=['area', 'outage_date'], name='core_powers_area_ff62eb_idx'), models.Index(fields=['outage_date', 'start_time'], name='core_powers_outage__b5b2c0_idx')],
            },
        ),
    ]
